### ISSUE TITLE
snkrs爬虫

### ISSUE THREAD

**Issue by mushroom11s** [cotide/snkrs-bot#1]
老哥 能不能看下你源码

**Comment by cotide** [comment]
不好意思，我还没时间写完，当时用POSTMAN 调通了能调用接口正常登陆。要花时间研究他接口API

**Comment by mushroom11s** [comment]
是的 每次发售抢成狗 想写爬虫了 他登陆请求啥的有什么麻烦的地方吗

**Comment by cotide** [comment]
他是前后端分离，主要要花时间分析它的接口。当时因为他的手机端我抓不了包，不知道他正确的请求。
后面我发现他可以PC登录进行授权，只要拿到访问的TOKEN，剩下就是不停请求接口。这部分我攻破了，想再分析他其他接口，但事情比较多，要忙完再写吧。你是用什么语言写爬虫的，抢到过吗？

**Comment by mushroom11s** [comment]
用python写 我主要是做java的  你的兼职项目需要人不 想挣外快

**Comment by cotide** [comment]
那你用的python脚本抢到过吗？Github 上抢鞋的代码都不能用，因为那边已经调整接口规则了

**Comment by mushroom11s** [comment]
没有 最近想写爬虫抢一下
